[BUGFIX] Use gecode depsolver for berks #patch
One resolver is more broken than the other. Currently, the ruby one
is annoying with

> ruby_solver.rb:80:in `block in resolve': undefined method `name' for nil:NilClass (NoMethodError)

So use the default gecode solver again :-(

Caused by berkshelf/solve#64